### ISSUE TITLE
Special Chars (ä, ö, ü) are displayed wrong (as question mark)

### ISSUE THREAD

**Issue by rbrixel** [SergeyTsalkov/meekrodb#107] opened 2024-07-26 13:18 UTC
Hello!

My mysql-database is utf8mb4_general_ci; the fields are varchars. I have texts in in like 'Pröll'.

In my php-script I initialize the db-object with:
`DB::$dsn = 'mysql:host=localhost;dbname=...';
DB::$user = '...';
DB::$password = '...';
DB::$encoding = 'utf8';`

The php-page is with bootstrap, so it is utf-8 and I double-checked it in vs-code that the file is utf-8.

When I echo the values from the database I get 'Pr�ll' instead of 'Pröll'.

What is the issue?

Composer says: "sergeytsalkov/meekrodb": "^3.0" (v3.0.1)

**Comment by Holmes-CC** [comment] 2024-07-26 14:24
I might depend on your MySQL version; however, after a quick search, documentation for MySQL 8.4 returned this:

```https://dev.mysql.com/doc/refman/8.4/en/charset-unicode-sets.html```

## _general_ci Versus _unicode_ci Collations

For any Unicode character set, operations performed using the xxx_general_ci collation are faster than those for the xxx_unicode_ci collation. For example, comparisons for the utf8mb4_general_ci collation are faster, but slightly less correct, than comparisons for utf8mb4_unicode_ci. The reason is that utf8mb4_unicode_ci supports mappings such as expansions; that is, when one character compares as equal to combinations of other characters. For example, ß is equal to ss in German and some other languages. utf8mb4_unicode_ci also supports contractions and ignorable characters. utf8mb4_general_ci is a legacy collation that does not support expansions, contractions, or ignorable characters. It can make only one-to-one comparisons between characters.

In my opinion, it might be your Collation causing the issue.

**Comment by rbrixel** [comment] 2024-07-26 14:34
Nope, it doesn't work :/

I changed the database coallition from utf8mb4_general_ci to utf8mb4_unicode_ci, changed one record from 'Söll' to 'Soell' and back again... but it is still 'S�ll' in the output...

**Comment by Holmes-CC** [comment] 2024-07-26 14:39
> Nope, it doesn't work :/
> 
> I changed the database collation from utf8mb4_general_ci to utf8mb4_unicode_ci, changed one record from 'Söll' to 'Soell' and back again... but it is still 'S�ll' in the output...

You may have to ensure your are using UTF-8 with html, table column collation as well? Are you rendering the response to terminal or html?

**Comment by SergeyTsalkov** [comment] 2024-07-26 21:47
I'm not able to reproduce this. I made this simple script to test it:
```php
DB::$dsn = 'mysql:host=localhost;dbname=meekrodb';
DB::$user = 'meekrodb';
DB::$password = 'meekrodb';

DB::query("DROP TABLE IF EXISTS mytest");
DB::query("
  CREATE TABLE mytest (
    id int not null auto_increment primary key,
    data varchar(255) not null
  )
");

DB::insert('mytest', ['data' => 'Pröll']);
echo DB::queryFirstField("SELECT data FROM mytest LIMIT 1");
```

Then I ran the script locally with `php -S localhost:8080 test.php` and went to http://localhost:8080 and it worked fine. Can you repeat this test (you may have to adjust it a bit if you're running it remotely) and confirm that it works for you?

**Comment by rbrixel** [comment] 2024-07-26 22:28
I ran the following test - only the following code without html in browser - and it works!

But in my main-html-file with bootstrap, I get the question-marks... I don't know why this is happening :/

`<?php
require ('./vendor/autoload.php');

// Meekro-DB
DB::$dsn = 'mysql:host=localhost;dbname=...';
DB::$user = '...';
DB::$password = '...';
DB::$encoding = 'utf8';

$query = "SELECT city FROM playingfields";
$results = DB::query($query);

foreach ($results as $row) {
    echo $row['city'] . "\n";
}`

**Comment by rbrixel** [comment] 2024-07-26 22:35
When I check the index.php-file on Mac (file -I filename), I get: `index.php: text/x-php; charset=utf-8` - so the file is utf-8.

I use for db `DB::$encoding = 'utf8';` and `<meta charset="utf-8">`... but as always question-marks...

**Comment by SergeyTsalkov** [comment] 2024-07-26 22:53
Unfortunately, figuring out this kind of thing is part of how you grow your skill as a programmer. We both agree that MeekroDB is fetching the right data. I can't really help because the problem could be anywhere in your application, and you just need to keep studying the problem or seek out programming help.

I'm closing this for now, but please let me know if you discover that MeekroDB is not returning the right data.

**Closed by SergeyTsalkov** 2024-07-26 22:53 UTC

**Comment by SergeyTsalkov** [comment] 2024-07-26 23:30
I don't mean to leave you hanging, though. If you wanted me to help you debug your project, I could. It's not open source work, so I would charge you an hourly rate, and you'd have to give me full access to your project. Please reach out by email if you want to do this-- my email is in the copyright notice on this project's php file.

**Comment by kkrell2016** [comment] 2025-01-07 16:43
> When I check the index.php-file on Mac (file -I filename), I get: `index.php: text/x-php; charset=utf-8` - so the file is utf-8.
> 
> I use for db `DB::$encoding = 'utf8';` and `<meta charset="utf-8">`... but as always question-marks...

Had the same issue. You have to change the dsn string by adding the encoding.

"mysql:host=localhost;dbname=mydb;charset=utf8"
