### ISSUE TITLE
Format specifier %t throws an exception on use.

### ISSUE THREAD

**Issue by mcgpj** [SergeyTsalkov/meekrodb#111] opened 2024-11-26 19:17 UTC
[Timestamp format specifier handler function](https://github.com/SergeyTsalkov/meekrodb/blob/8413fe472e3e737f84c780dee49d5afffb88008d/db.class.php#L601) throws an exception on use, due to supplying non-array argument to the [MeekroDBParsedQuery](https://github.com/SergeyTsalkov/meekrodb/blob/8413fe472e3e737f84c780dee49d5afffb88008d/db.class.php#L1386) class constructor. Issue can be solved by wrapping the second argument with **array()** function in the timestamp format handler.
![изображение](https://github.com/user-attachments/assets/a540b86d-40fe-443b-b4d6-abd99c206c6d)
![изображение](https://github.com/user-attachments/assets/98be6132-c767-4c67-956c-98bdde6c9f3d)

**Comment by dmsuslov74** [comment] 2024-11-26 19:22
I confirm it. The problem is solved by the following change:

`$ diff ./db.class.php ./db.class.php.fix 
595c595
<         return new MeekroDBParsedQuery('?', $t->sanitizeTS($arg));
---
>         return new MeekroDBParsedQuery('?', array($t->sanitizeTS($arg)));
`

**Comment by SergeyTsalkov** [comment] 2024-11-27 03:02
Thanks for the report, it's resolved in dev-master and will hopefully be part of a minor release later this week.

**Closed** 2024-11-27 03:01 UTC
